version: '3.8'

services:
  api:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./models:/models
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  jupyter: 
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./models:/models
    command: start-notebook.sh --NotebookApp.token=''
  

volumes:
  models:
    driver: local


