version: '3.9'

services:
  jupyter:
    build:
      context: .
    container_name: mlops_jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./work:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]




